version: '3.6'

services:
  client:
    image: node:12-slim
    working_dir: /client
    volumes:
      - ./client:/client      
    command:
      npm run-script build-watch
    environment:
      NODE_ENV: development

  server:
    image: golang:1.14.2
    container_name: golang
    working_dir: /server
    volumes:
      - ./server:/server
    command: bash -c "sleep infinity"

  db:
    image: firebase
    build: ./firebase
    container_name: firebase
    working_dir: /code
    volumes:
      - ./firebase:/code
      - ./firebase/.config:/home/node/.config
      - ./firebase/.cache:/home/node/.cache
    ports:
      - 9005:9005
      - 9000:9000
      - 4400:4400
    command: firebase emulators:start
