version: '3.6'

services:
  client:
    image: node:12-slim
    container_name: vue-client
    working_dir: /client
    volumes:
      - ./client:/client      
    command:
      npm run-script serve
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  server:
    image: golang:1.14.2
    build: ./server
    container_name: go-server
    working_dir: /server
    volumes:
      - ./client/dist:/client/dist
      - ./server:/server
    ports:
      - 8080:8080
    command: gin --appPort 8080 --all -i run .
    #command: bash -c "sleep infinity"


  db:
    image: firebase
    build: ./firebase
    container_name: firebase-db
    working_dir: /server
    volumes:
      - ./firebase:/server
      - ./firebase/.config:/home/node/.config
      - ./firebase/.cache:/home/node/.cache
    ports:
      - 9005:9005
      - 9000:9000
      - 4400:4400
      - 4000:4000
    command: firebase emulators:start
