name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: do NPM install
      run: npm install
    - name: Build the Docker image
      run: docker build . --file https://github.com/jtknutti/uno/Dockerfile --tag my-image-name:$(date +%s)
