name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker-compose build

      - name: Install dependencies
        run: cd client; chmod +x install.sh; ./install.sh

      - name: Start the application
        run: docker-compose up -d

      - name: start the integration tests
        run: docker-compose -f integration-tests.yml up